version: '3.7'

services:
        postgres:
                image: postgres:13-alpine
                container_name: synapse-postgres
                volumes:
                        - ./postgres_data:/var/lib/postgresql/data
                environment:
                        POSTGRES_USER: ${DB_USER}
                        POSTGRES_PASSWORD: ${DB_PASSWORD}
                        POSTGRES_DB: ${DB_NAME}
                        PGDATA: /var/lib/postgresql/data/pgdata
                        TZ: Asia/Tehran
                networks:
                        - synapse
                restart: unless-stopped
        redis:
                image: redis:6-alpine
                container_name: synapse-redis
                networks:
                        - synapse
                environment:
                        TZ: Asia/Tehran
                restart: unless-stopped
        web:
                image: vectorim/element-web
                container_name: synapse-web
                volumes:
                        - ./element-web/config.json:/app/config.json
                        - ./element-web/default.conf:/etc/nginx/conf.d/default.conf
                        - ./certificates:/etc/nginx/conf.d/certificates
                ports:
                        - 443:443
                        - 80:80
                networks:
                        - synapse
                environment:
                        TZ: Asia/Tehran
                restart: unless-stopped
        synapse:
                image: matrixdotorg/synapse
                container_name: synapse-matrix
                volumes:
                        - ./matrix:/data
                        - ./certificates:/data/certificates
                networks:
                        - synapse
                environment:
                        TZ: Asia/Tehran
                restart: unless-stopped

networks:
        synapse:
                driver: bridge
