version: '3.7'

services:
        postgres:
                image: postgres:13-alpine
                container_name: postgres
                volumes:
                        - ./postgres_data:/var/lib/postgresql/data
                environment:
                        POSTGRES_USER: ${DB_USER}
                        POSTGRES_PASSWORD: ${DB_PASSWORD}
                        POSTGRES_DB: ${DB_NAME}
                        PGDATA: /var/lib/postgresql/data/pgdata
                        TZ: Asia/Tehran
                networks:
                        - synapse
                restart: unless-stopped
        redis:
                image: redis:6-alpine
                container_name: redis
                networks:
                        - synapse
                environment:
                        TZ: Asia/Tehran
                restart: unless-stopped
        web:
                image: vectorim/element-web:v1.11.0
                container_name: web
                volumes:
                        - ./element-web/config.json:/app/config.json
                        - ./element-web/default.conf:/etc/nginx/conf.d/default.conf
                        - ./element-web/nginx.conf:/etc/nginx/nginx.conf
                        - ./certificates:/etc/nginx/conf.d/certificates
                ports:
                        - 443:443
                        - 80:80
                networks:
                        - synapse
                environment:
                        TZ: Asia/Tehran
                restart: unless-stopped
                depends_on:
                        - synapse
        synapse:
                image: matrixdotorg/synapse:v1.60.0
                container_name: synapse
                volumes:
                        - ./synapse:/data
                        - ./certificates:/data/certificates
                networks:
                        - synapse
                environment:
                        TZ: Asia/Tehran
                restart: unless-stopped
                depends_on:
                        - postgres
                        - redis

networks:
        synapse:
                driver: bridge
